//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MocaDaoDemo.Models
{
    using Moca.Db;
    using Moca.Db.Attr;
    using System.ComponentModel;
    using System.Runtime.CompilerServices;


    ///  <summary> 
    ///  TrnTableRow Entity 
    ///  </summary> 
    ///  <remarks></remarks> 
    ///  <history> 
    ///  </history> 
    public class TrnTableRow : System.ComponentModel.INotifyPropertyChanged
    {

        #region  Declare 

        /// <summary>
        /// テーブル定義
        /// </summary>
        /// <remarks>
        /// SQL自動生成や Windows Forms で ControlBinder 使ったときの検証等に利用されます。
        /// </remarks>
        static MocaDaoDemo.Db.Definitions.Tables.ITrnTableDefinition _def;

        private int _id;

        private string _name;

        private bool _flg;

        private decimal _amountOfMoney;

        private System.DateTime? _insertDate;

        private System.DateTime? _updateDate;

        #endregion

        #region  Property 

        ///  <summary> 
        ///  Id (Id) Property. 
        ///  </summary> 
        [Column("Id")]
        public int Id
        {
            get
            {
                return this._id;
            }
            set
            {
                this._id = value;
                OnPropertyChanged();
            }
        }

        ///  <summary> 
        ///  Name (Name) Property. 
        ///  </summary> 
        [Column("Name")]
        public string Name
        {
            get
            {
                return this._name;
            }
            set
            {
                this._name = value;
                OnPropertyChanged();
            }
        }

        ///  <summary> 
        ///  Flg (Flg) Property. 
        ///  </summary> 
        [Column("Flg")]
        public bool Flg
        {
            get
            {
                return this._flg;
            }
            set
            {
                this._flg = value;
                OnPropertyChanged();
            }
        }

        ///  <summary> 
        ///  AmountOfMoney (AmountOfMoney) Property. 
        ///  </summary> 
        [Column("AmountOfMoney")]
        public decimal AmountOfMoney
        {
            get
            {
                return this._amountOfMoney;
            }
            set
            {
                this._amountOfMoney = value;
                OnPropertyChanged();
            }
        }

        ///  <summary> 
        ///  InsertDate (InsertDate) Property. 
        ///  </summary> 
        [Column("InsertDate")]
        public System.DateTime? InsertDate
        {
            get
            {
                return this._insertDate;
            }
            set
            {
                this._insertDate = value;
                OnPropertyChanged();
            }
        }

        ///  <summary> 
        ///  UpdateDate (UpdateDate) Property. 
        ///  </summary> 
        [Column("UpdateDate")]
        public System.DateTime? UpdateDate
        {
            get
            {
                return this._updateDate;
            }
            set
            {
                this._updateDate = value;
                OnPropertyChanged();
            }
        }

        #endregion

        #region  PropertyChanged 

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName()] string name = null)
        {
            if ((PropertyChanged != null))
            {
                PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(name));
            }
        }

        #endregion
    }
}
